package com.vaidh.customer.model.enums;

public enum ProductCategory {
    UNKNOWN, TABLET, LIQUID, CAPSULES, INJECTION, INHALERS, LAB, HOME_CARE,
    BABY_CARE,
    COVID_ESSENTIALS,
    HEALTH_CARE_DEVICES,
    PERSONAL_CARE,
    AYURVEDIC_CARE,
    MOTHER_AND_BABY_CARE,
    ACCESSORIES_AND_WEARABLES,
    SKIN_CARE,
    DIABETIC_CARE,
    HEALTH_CONDITION,
    SEXUAL_WELLNESS,
    FITNESS_AND_SUPPLEMENT,
    ELDER_CARE,
    SURGICAL_AND_DRESSING,
    PET_CARE
}
