version: '3'
services:
  myspringapp:
    image: my-vaidh-customer
    build: .
    ports:
      - "8080:8080"
    restart: always
    #network_mode: host
    environment:
      - PSQL_DB_SERVER=host.docker.internal
      - PSQL_DB_NAME=vaidh
      - PSQL_DB_USERNAME=postgres
      - PSQL_DB_PW=123
      - JWT_SECRET=abcd123abcvaidh
      - FIREBASE_URL=https://vaidh-d7457-default-rtdb.firebaseio.com
      - VAIDH_MAIL_PW=Vaidh123
      - VAIDH_MAIL_ID=vaidh.notify@gmail.com